# Generated by Django 5.1.2 on 2024-11-07 00:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('quantidades', models.IntegerField()),
                ('preco', models.FloatField()),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
    ]
